FROM python:3.11-slim

WORKDIR /app

COPY ui-services/streamlit/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ui-services/streamlit/ .
COPY ui-services/config/ config/

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]
